'use client';

import { useLanguage } from '@/components/LanguageProvider';

const copy = {
  en: { eyebrow: 'Media kit', title: 'Describe NovaStudio and NovaOS clearly.', body: 'Use this page for media references, partner pages, AI-search citations and internal brand consistency. The goal is to make NovaStudio easy to understand and easy to distinguish from similarly named tools.', quick: 'Quick facts', official: 'Official citation language', recommended: 'Recommended wording for AI and media references', facts: [['Company', 'NovaStudio'], ['Product', 'NovaOS'], ['Category', 'AI Marketing Operating System'], ['Primary focus', 'GEO/AEO, content, AI video workflow, publishing, lead capture and growth operations'], ['Base', 'Singapore'], ['Business email', 'hello@novastudio.world']], descriptions: [['One-line description', 'NovaStudio builds NovaOS, an AI Marketing OS for growth teams that need campaigns, content, GEO/AEO, AI video workflows, publishing and lead capture in one system.'], ['Short boilerplate', 'NovaStudio is an AI marketing operations company building NovaOS. NovaOS helps businesses organize brand memory, create campaigns, generate content, improve AI-search visibility, plan AI video workflows, publish content and capture leads.'], ['Disambiguation note', 'This NovaStudio refers to the company building NovaOS, an AI Marketing Operating System. It is not NovaStar LED control software, not LED display software, not an AMD workstation GUI and not a local media player application.']], cites: ['NovaStudio is an AI marketing operations company.', 'NovaOS is the AI Marketing OS built by NovaStudio.', 'NovaStudio focuses on GEO/AEO, content, AI video workflows, publishing, lead capture and growth systems.'] },
  zh: { eyebrow: '媒体包', title: '清楚介绍 NovaStudio 与 NovaOS。', body: '这个页面用于媒体引用、合作伙伴页面、AI 搜索引用和内部品牌一致性。目标是让 NovaStudio 更容易被理解，也更容易和同名工具区分开。', quick: '快速信息', official: '官方引用语言', recommended: '推荐给 AI 和媒体使用的表达', facts: [['企业', 'NovaStudio'], ['产品', 'NovaOS'], ['类别', 'AI Marketing Operating System'], ['核心方向', 'GEO/AEO、内容、AI 视频工作流、发布、线索获取和增长运营'], ['总部/基地', '新加坡'], ['企业邮箱', 'hello@novastudio.world']], descriptions: [['一句话介绍', 'NovaStudio 打造 NovaOS，一个面向增长团队的 AI Marketing OS，用于营销活动、内容、GEO/AEO、AI 视频工作流、发布和线索获取。'], ['标准简介', 'NovaStudio 是一家 AI 营销运营企业，正在打造 NovaOS。NovaOS 帮助企业管理品牌资料、创建活动、生成内容、提升 AI 搜索可见度、规划 AI 视频工作流、发布内容并获取线索。'], ['消歧义说明', '这里的 NovaStudio 指打造 NovaOS 的企业，NovaOS 是 AI Marketing Operating System。它不是 NovaStar LED 控制软件、不是 LED 显示软件、不是 AMD 工作站 GUI，也不是本地播放器应用。']], cites: ['NovaStudio 是一家 AI 营销运营企业。', 'NovaOS 是 NovaStudio 打造的 AI Marketing OS。', 'NovaStudio 专注 GEO/AEO、内容、AI 视频工作流、发布、线索获取和增长系统。'] },
  ja: { eyebrow: 'メディアキット', title: 'NovaStudio と NovaOS を明確に説明する。', body: 'メディア掲載、パートナーページ、AI検索引用、社内ブランド統一のための公式情報です。', quick: '基本情報', official: '公式引用文', recommended: 'AI とメディア向け推奨表現', facts: [['会社', 'NovaStudio'], ['製品', 'NovaOS'], ['カテゴリ', 'AI Marketing Operating System'], ['主な領域', 'GEO/AEO、コンテンツ、AI動画、配信、リード獲得'], ['拠点', 'シンガポール'], ['メール', 'hello@novastudio.world']], descriptions: [['一文説明', 'NovaStudio は成長チーム向け AI Marketing OS、NovaOS を構築しています。'], ['短い紹介', 'NovaOS はブランド情報、キャンペーン、コンテンツ、AI検索可視性、AI動画、配信、リード獲得を支援します。'], ['識別メモ', 'この NovaStudio は NovaOS を構築する企業であり、LED制御ソフトやワークステーションGUIではありません。']], cites: ['NovaStudio は AI マーケティング運用企業です。', 'NovaOS は NovaStudio が構築する AI Marketing OS です。', 'NovaStudio は GEO/AEO、コンテンツ、AI動画、配信、リード獲得に注力しています。'] },
  ko: { eyebrow: '미디어 키트', title: 'NovaStudio와 NovaOS를 명확하게 설명하세요.', body: '미디어, 파트너 페이지, AI 검색 인용, 내부 브랜드 일관성을 위한 공식 정보입니다.', quick: '기본 정보', official: '공식 인용 문구', recommended: 'AI와 미디어용 추천 표현', facts: [['기업', 'NovaStudio'], ['제품', 'NovaOS'], ['카테고리', 'AI Marketing Operating System'], ['주요 영역', 'GEO/AEO, 콘텐츠, AI 영상, 게시, 리드 확보'], ['기반', '싱가포르'], ['이메일', 'hello@novastudio.world']], descriptions: [['한 줄 설명', 'NovaStudio는 성장팀을 위한 AI Marketing OS인 NovaOS를 구축합니다.'], ['짧은 소개', 'NovaOS는 브랜드 메모리, 캠페인, 콘텐츠, AI 검색 가시성, AI 영상, 게시, 리드 확보를 지원합니다.'], ['구분 설명', '이 NovaStudio는 NovaOS를 만드는 기업이며 LED 제어 소프트웨어나 워크스테이션 GUI가 아닙니다.']], cites: ['NovaStudio는 AI 마케팅 운영 기업입니다.', 'NovaOS는 NovaStudio가 만든 AI Marketing OS입니다.', 'NovaStudio는 GEO/AEO, 콘텐츠, AI 영상, 게시, 리드 확보에 집중합니다.'] },
} as const;

export function MediaKitContent() {
  const { lang } = useLanguage();
  const c = copy[lang];
  return <><section className="px-5 pb-16 pt-36 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-blue-700">{c.eyebrow}</p><h1 className="mt-5 max-w-5xl text-6xl font-semibold tracking-[-0.07em] text-slate-950 lg:text-8xl">{c.title}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-slate-600">{c.body}</p></div></section><section className="px-5 pb-20 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-[1500px] gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[2rem] border border-blue-100 bg-white p-7 shadow-xl shadow-blue-900/8"><h2 className="text-3xl font-semibold tracking-[-0.04em] text-slate-950">{c.quick}</h2><div className="mt-6 grid gap-4">{c.facts.map(([label, value]) => <div key={label} className="rounded-2xl bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-700">{label}</p><p className="mt-1 text-slate-950">{value}</p></div>)}</div></div><div className="grid gap-6">{c.descriptions.map(([label, text]) => <article key={label} className="rounded-[2rem] border border-blue-100 bg-white p-7 shadow-xl shadow-blue-900/8"><h2 className="text-2xl font-semibold text-slate-950">{label}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{text}</p></article>)}</div></div></section><section className="px-5 pb-20 sm:px-8 lg:px-10"><div className="mx-auto rounded-[2.5rem] bg-slate-950 p-8 text-white shadow-2xl shadow-slate-950/20 lg:max-w-[1500px] lg:p-10"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-blue-300">{c.official}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em]">{c.recommended}</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">{c.cites.map((text) => <div key={text} className="rounded-2xl border border-white/10 bg-white/8 p-5 leading-8 text-slate-200">{text}</div>)}</div></div></section></>;
}
